<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/10_backpropagation_regression_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Flatten

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=[['cgpa', 'profile_score', 'lpa']])

In [3]:
df.head()

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [8]:
model=Sequential()
model.add(Dense(2,activation="relu",input_dim=2))
model.add(Dense(1,activation="linear"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.get_weights()

[array([[ 0.36212826,  0.13573861],
        [ 0.19110215, -1.0560712 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.65109664],
        [ 1.260722  ]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
new_weights=[np.array([[ 0.1, -0.1],
        [-1.1 ,  1.1  ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1  ],
        [ 0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [15]:
model.set_weights(new_weights)

In [16]:
model.get_weights()

[array([[ 0.1, -0.1],
        [-1.1,  1.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [17]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [18]:
X1=df.iloc[:,0:2].values
y1=df.iloc[:,-1].values

In [19]:
model.fit(X1,y1,epochs=75,batch_size=1,verbose=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 20.8805
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 20.4543
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 19.9981
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 19.5485
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 19.0769
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 18.6562
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 18.2295
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 17.7686
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.3400 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16.9166 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 16.4351
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 16.0268
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 15.6204
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 15.1762 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.7682
Epoch 16/75
4/4 

In [20]:
model.get_weights()

[array([[ 0.1      ,  0.1693137],
        [-1.1      ,  1.3585134]], dtype=float32),
 array([0.        , 0.26630268], dtype=float32),
 array([[0.1      ],
        [0.3163394]], dtype=float32),
 array([0.20457678], dtype=float32)]