<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/10_backpropagation_regression_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Flatten

In [22]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=[['cgpa', 'profile_score', 'lpa']])

In [23]:
df.head()

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [28]:
model=Sequential()
model.add(Dense(2,activation="linear",input_dim=2))
model.add(Dense(1,activation="linear"))

In [29]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.get_weights()

[array([[-0.38217622,  1.0936872 ],
        [ 0.11064017,  1.2172104 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.3007408 ],
        [-0.17394507]], dtype=float32),
 array([0.], dtype=float32)]

In [31]:
new_weights=[np.array([[ 0.1, -0.1],
        [-1.1 ,  1.1  ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1  ],
        [ 0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [32]:
model.set_weights(new_weights)

In [33]:
model.get_weights()

[array([[ 0.1, -0.1],
        [-1.1,  1.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [34]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [35]:
X1=df.iloc[:,0:2].values
y1=df.iloc[:,-1].values

In [36]:
model.fit(X1,y1,epochs=75,batch_size=1,verbose=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 31.0701  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30.1087 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 28.9648
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 28.0107 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.1262 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.1773
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.1330
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 24.2603
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.3763
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22.5647 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 21.7050 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.9450
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.1037
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 19.3427
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 18.5809
Epoch 16/75
4/

In [37]:
model.get_weights()

[array([[ 0.1352748,  0.1419201],
        [-1.0695677,  1.3327787]], dtype=float32),
 array([0.0328842, 0.2396496], dtype=float32),
 array([[-0.07262415],
        [ 0.29426864]], dtype=float32),
 array([0.18472248], dtype=float32)]