<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/LSTM_Own.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from keras.utils import to_categorical

In [7]:
feqs="""my name is ajay
I am from Bihar"""


In [8]:
feqs

'my name is ajay\nI am from Bihar'

In [9]:
tokenizer=Tokenizer()

In [10]:
tokenizer.fit_on_texts([feqs])

In [11]:
tokenizer.word_index

{'my': 1,
 'name': 2,
 'is': 3,
 'ajay': 4,
 'i': 5,
 'am': 6,
 'from': 7,
 'bihar': 8}

In [20]:
input_sequences=[]
for sentence in feqs.split("\n"):
    seq_text=tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1,len(seq_text)):
      input_sequences.append(seq_text[:i+1])



In [21]:
input_sequences

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7], [5, 6, 7, 8]]

In [22]:
length=[len(x) for x in input_sequences]

In [24]:
max_length=max(length)

In [25]:
max_length

4

In [26]:
padded_input_sequences=pad_sequences(input_sequences, maxlen=max_length, padding="pre")

In [27]:
padded_input_sequences

array([[0, 0, 1, 2],
       [0, 1, 2, 3],
       [1, 2, 3, 4],
       [0, 0, 5, 6],
       [0, 5, 6, 7],
       [5, 6, 7, 8]], dtype=int32)

In [28]:
X=padded_input_sequences[:,:-1]
y=padded_input_sequences[:,-1]

In [29]:
X

array([[0, 0, 1],
       [0, 1, 2],
       [1, 2, 3],
       [0, 0, 5],
       [0, 5, 6],
       [5, 6, 7]], dtype=int32)

In [30]:
y

array([2, 3, 4, 6, 7, 8], dtype=int32)

In [31]:
X.shape

(6, 3)

In [35]:
len(tokenizer.word_index)

8

In [36]:
y.shape

(6,)

In [37]:
y=to_categorical(y, num_classes=len(tokenizer.word_index)+1)

In [38]:
y

array([[0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [44]:
model=Sequential()
model.add(Embedding(len(tokenizer.word_index)+1, 4, input_length=X.shape[1]))
model.add(LSTM(150))
model.add(Dense(len(tokenizer.word_index)+1, activation="softmax"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [45]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [46]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])


In [47]:
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 2.1977
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.1667 - loss: 2.1946
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.1667 - loss: 2.1914
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.1667 - loss: 2.1882
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3333 - loss: 2.1848
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3333 - loss: 2.1813
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.3333 - loss: 2.1775
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.3333 - loss: 2.1735
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.3333 - loss: 2.1692
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.3333 - loss: 2.1646
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.3333 - loss: 2.1596
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3333 - 

In [69]:
import time
text = "i"

for i in range(3):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=3, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
i am
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
i am from
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
i am from bihar


In [58]:
import time
text = "i am"
 # tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
print(token_text)


[5, 6]


In [63]:
  # padding
padded_token_text = pad_sequences([token_text], maxlen=3, padding='pre')
print(padded_token_text)


[[0 5 6]]


In [64]:

  # predict
pos = np.argmax(model.predict(padded_token_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
