<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/backwardpropgration_regression_custom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [379]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



In [380]:
df=pd.DataFrame({
    "cgpa":[8,7,6,5],
    "profile_score":[8,9,10,12],
    "lpa":[4,5,6,7]

})

In [381]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [382]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  L=len(layer_dims)
  parameters={}

  for l in range(1,L):
    parameters['W'+str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b'+str(l)]=np.zeros((layer_dims[l],1))*0.1
  return parameters

In [391]:
parameters=initialize_parameters([2,2,1])

In [392]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [385]:
#print(parameters['b1'])


In [386]:
#print(parameters['W2'])


In [387]:
#print(parameters['b2'])

In [388]:
#len(parameters)

In [389]:
def linear_forward(W,A_prev,b):

  Z=np.dot(W.T,A_prev)+b
  return Z

In [367]:
def L_layer_forward(X, parameters):

  A = X

  L=len(parameters)//2

  for l in range(1,L+1):
    A_prev = A
    #print("A"+str(l-1)+": ", A_prev)
    W1=parameters['W'+str(l)]
    b1=parameters['b'+str(l)]

    #print("W"+str(l)+": ", W1)
    #print("b"+str(l)+": ", b1)

    A=linear_forward(W1,A_prev,b1)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
  return A,A_prev

In [368]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]


In [396]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] +  (0.001 * 2 * (y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] +  (0.001 * 2 * (y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] +  (0.001 * 2 * (y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] +  (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] +  (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] +  (0.001 * 2 * (y-y_hat))*parameters['W2'][0][0]


  parameters['W1'][1][0] = parameters['W1'][1][0] +  (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] +  (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] +  (0.001 * 2 * (y-y_hat))*parameters['W2'][1][0]


In [397]:
update_parameters(parameters,y,y_hat,A1,X)


In [398]:
parameters

{'W1': array([[0.28108331, 0.41727494],
        [0.29676652, 0.44720893]]),
 'b1': array([[0.03035128],
        [0.03311122]]),
 'W2': array([[0.44170771],
        [0.52524219]]),
 'b2': array([[0.12179977]])}

In [399]:
X=df[['cgpa','profile_score']].values[1].reshape(2,1)
y=df[['lpa']].values[1][0]
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]


In [400]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.27592334, 0.4106407 ],
        [0.29065956, 0.43935713]]),
 'b1': array([[0.02961414],
        [0.0322388 ]]),
 'W2': array([[0.43377368],
        [0.51338249]]),
 'b2': array([[0.12010041]])}

In [401]:
X=df[['cgpa','profile_score']].values[2].reshape(2,1)
y=df[['lpa']].values[2][0]
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]


In [402]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.27776446, 0.41370922],
        [0.29284287, 0.44299599]]),
 'b1': array([[0.029921  ],
        [0.03260268]]),
 'W2': array([[0.43699793],
        [0.51822029]]),
 'b2': array([[0.12080259]])}

In [403]:
X=df[['cgpa','profile_score']].values[3].reshape(2,1)
y=df[['lpa']].values[3][0]
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]


In [404]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.28168579, 0.42312042],
        [0.29751731, 0.45421463]]),
 'b1': array([[0.03070526],
        [0.03353757]]),
 'W2': array([[0.44567834],
        [0.53127226]]),
 'b2': array([[0.12256231]])}

In [405]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
print(parameters)
epochs = 5
Loss=[]

for i in range(epochs):
  for j in range(df.shape[0]):
    X=df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['lpa']].values[j][0]

    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)
  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())
parameters

{'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}
Epoch -  1 Loss -  26.28249792398698
Epoch -  2 Loss -  22.860375886103892
Epoch -  3 Loss -  18.62020873601177
Epoch -  4 Loss -  14.811546878285448
Epoch -  5 Loss -  12.113206585198048


{'W1': array([[0.273603  , 0.3993222 ],
        [0.28787155, 0.42586102]]),
 'b1': array([[0.02885522],
        [0.03133223]]),
 'W2': array([[0.42574893],
        [0.50219328]]),
 'b2': array([[0.11841278]])}

**Keras Implementation**

In [406]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [407]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [408]:
model=Sequential()

In [409]:
model.add(Dense(2,activation='linear', input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [410]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [411]:
model.get_weights()

[array([[-0.8119631 , -1.0513492 ],
        [-0.64261216,  0.31343114]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.6472262],
        [ 0.8650485]], dtype=float32),
 array([0.], dtype=float32)]

In [412]:
 new_weights=[np.array([[ 0.1, -0.1],
        [-1.1 ,  1.1  ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1  ],
        [ 0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [413]:
model.set_weights(new_weights)

In [414]:
model.get_weights()

[array([[ 0.1, -0.1],
        [-1.1,  1.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [415]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [416]:
X1=df.iloc[:,0:2].values
y1=df.iloc[:,-1].values

In [417]:
model.fit(X1,y1,epochs=75,batch_size=1,verbose=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 34.8015  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.7071 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.1234 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.0198 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.9284 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 32.1151 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.9128 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.1042 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.5875 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.2377 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.2947 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.6543 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.4668 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.7185
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.4415 
Epoch 16/75
4/4 ━━━

In [393]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}