<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/backwardpropgration_regression_custom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



In [3]:
df=pd.DataFrame({
    "cgpa":[8,7,6,5],
    "profile_score":[8,9,10,12],
    "lpa":[4,5,6,7]

})

In [4]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [96]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  L=len(layer_dims)
  parameters={}

  for l in range(1,L):
    parameters['W'+str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b'+str(l)]=np.zeros((layer_dims[l],1))*0.1
  return parameters

In [98]:
parameters=initialize_parameters([2,2,1])

In [103]:
print(parameters['W1'])

[[0.1 0.1]
 [0.1 0.1]]


In [104]:
print(parameters['b1'])


[[0.]
 [0.]]


In [105]:
print(parameters['W2'])


[[0.1]
 [0.1]]


In [106]:
print(parameters['b2'])

[[0.]]


In [107]:
len(parameters)

4

In [174]:
def linear_forward(W,A_prev,b):

  Z=np.dot(W.T,A_prev)+b
  return Z

In [321]:
def L_layer_forward(X, parameters):

  A = X

  L=len(parameters)//2

  for l in range(1,L+1):
    A_prev = A
    #print("A"+str(l-1)+": ", A_prev)
    W1=parameters['W'+str(l)]
    b1=parameters['b'+str(l)]

    #print("W"+str(l)+": ", W1)
    #print("b"+str(l)+": ", b1)

    A=linear_forward(W1,A_prev,b1)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
  return A,A_prev

In [213]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]


In [283]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] +  (0.001 * 2 * (y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] +  (0.001 * 2 * (y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] +  (0.001 * 2 * (y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] +  (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] +  (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] +  (0.001 * 2 * (y-y_hat))*parameters['W2'][0][0]


  parameters['W1'][1][0] = parameters['W1'][1][0] +  (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] +  (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] +  (0.001 * 2 * (y-y_hat))*parameters['W2'][1][0]


In [284]:
update_parameters(parameters,y,y_hat,A1,X)


In [286]:
parameters

{'W1': array([[0.12598445, 0.12598445],
        [0.11524285, 0.11524285]]),
 'b1': array([[0.00324806],
        [0.00190536]]),
 'W2': array([[0.15888 ],
        [0.135328]]),
 'b2': array([[0.02208]])}

In [297]:
X=df[['cgpa','profile_score']].values[1].reshape(2,1)
y=df[['lpa']].values[1][0]
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]


A0:  [[7]
 [9]]
W1:  [[0.12598445 0.12598445]
 [0.11524285 0.11524285]]
b1:  [[0.00324806]
 [0.00190536]]
A1:  [[1.9223249]
 [1.9209822]]
****************************************
A1:  [[1.9223249]
 [1.9209822]]
W2:  [[0.15888 ]
 [0.135328]]
b2:  [[0.02208]]
A2:  [[0.58746166]]
****************************************


In [298]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.13684735, 0.13995103],
        [0.12465008, 0.12733786]]),
 'b1': array([[0.0047999 ],
        [0.00324925]]),
 'W2': array([[0.17584466],
        [0.15228082]]),
 'b2': array([[0.03090508]])}

In [299]:
X=df[['cgpa','profile_score']].values[2].reshape(2,1)
y=df[['lpa']].values[2][0]
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]


A0:  [[ 6]
 [10]]
W1:  [[0.13684735 0.13995103]
 [0.12465008 0.12733786]]
b1:  [[0.0047999 ]
 [0.00324925]]
A1:  [[2.07238483]
 [2.11633409]]
****************************************
A1:  [[2.07238483]
 [2.11633409]]
W2:  [[0.17584466]
 [0.15228082]]
b2:  [[0.03090508]]
A2:  [[0.71759997]]
****************************************


In [300]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.14938179, 0.16084176],
        [0.13572027, 0.14578817]]),
 'b1': array([[0.00688897],
        [0.00509428]]),
 'W2': array([[0.197739  ],
        [0.17463946]]),
 'b2': array([[0.04146988]])}

In [301]:
X=df[['cgpa','profile_score']].values[3].reshape(2,1)
y=df[['lpa']].values[3][0]
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]


A0:  [[ 5]
 [12]]
W1:  [[0.14938179 0.16084176]
 [0.13572027 0.14578817]]
b1:  [[0.00688897]
 [0.00509428]]
A1:  [[2.38244114]
 [2.55876118]]
****************************************
A1:  [[2.38244114]
 [2.55876118]]
W2:  [[0.197739  ]
 [0.17463946]]
b2:  [[0.04146988]]
A2:  [[0.95943207]]
****************************************


In [302]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.16306498, 0.19368142],
        [0.14813679, 0.17558782]]),
 'b1': array([[0.00962561],
        [0.00757758]]),
 'W2': array([[0.22652159],
        [0.2055522 ]]),
 'b2': array([[0.05355101]])}

In [324]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5
Loss=[]

for i in range(epochs):
  for j in range(df.shape[0]):
    X=df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['lpa']].values[j][0]

    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)
  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())
parameters

Epoch -  1 Loss -  26.28249792398698
Epoch -  2 Loss -  22.860375886103892
Epoch -  3 Loss -  18.62020873601177
Epoch -  4 Loss -  14.811546878285448
Epoch -  5 Loss -  12.113206585198048


{'W1': array([[0.273603  , 0.3993222 ],
        [0.28787155, 0.42586102]]),
 'b1': array([[0.02885522],
        [0.03133223]]),
 'W2': array([[0.42574893],
        [0.50219328]]),
 'b2': array([[0.11841278]])}