<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/rnn_sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow import keras
from keras import layers
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN



In [8]:
model= Sequential()

model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1, activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.get_weights()[0].shape

(5, 3)

In [13]:
model.get_weights()[0]

array([[-0.76972497,  0.22721499, -0.51784754],
       [-0.70533377, -0.6050279 , -0.25274277],
       [-0.38227335,  0.672919  , -0.8290812 ],
       [-0.13510501,  0.8206641 , -0.5249423 ],
       [ 0.55810934,  0.6475522 , -0.50142825]], dtype=float32)

In [14]:
model.get_weights()[1]

array([[-0.49678767, -0.64967734,  0.5754313 ],
       [-0.1608779 ,  0.720483  ,  0.67455363],
       [ 0.85283065, -0.24253583,  0.4624459 ]], dtype=float32)

In [15]:
model.get_weights()[1].shape

(3, 3)

In [16]:
model.get_weights()[2].shape

(3,)

In [17]:
model.get_weights()[2]

array([0., 0., 0.], dtype=float32)

In [19]:
model.get_weights()[3].shape

(3, 1)

In [20]:
model.get_weights()[4]

array([0.], dtype=float32)

In [21]:
model.get_weights()[4].shape

(1,)