<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/Simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [164]:
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow import keras
from keras.layers import SimpleRNN,Dense,Embedding,Flatten
from keras.models import Sequential

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences

In [165]:
docs=["i am ajay",
      "i am from india"]

In [245]:
token=Tokenizer()

In [246]:
token.fit_on_texts(docs)

In [247]:
token.word_index

{'i': 1, 'am': 2, 'ajay': 3, 'from': 4, 'india': 5}

In [248]:
token.document_count

2

In [249]:
sequence=token.texts_to_sequences(docs)

In [250]:
sequence

[[1, 2, 3], [1, 2, 4, 5]]

In [251]:
len(sequence[1])

4

In [252]:
token.word_index

{'i': 1, 'am': 2, 'ajay': 3, 'from': 4, 'india': 5}

In [253]:
len(token.word_index)

5

In [254]:
sequence=pad_sequences(sequence, padding="post")

In [255]:
sequence

array([[1, 2, 3, 0],
       [1, 2, 4, 5]], dtype=int32)

In [256]:
len(token.word_index)

5

**Embedded Encoding**

In [257]:
model=Sequential()
model.add(Embedding(len(token.word_index)+1,output_dim=2,input_shape=(4,)))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation="sigmoid"))

In [258]:
model.summary()

Model: "sequential_33"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_20 (Embedding)        │ (None, 4, 2)           │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_26 (SimpleRNN)       │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,165 (4.55 KB)

 Trainable params: 1,165 (4.55 KB)

 Non-trainable params: 0 (0.00 B)

In [259]:
X_train=sequence

In [260]:
X_train

array([[1, 2, 3, 0],
       [1, 2, 4, 5]], dtype=int32)

In [261]:
y_train=np.array([1,0])

In [262]:
model.compile(loss='binary_crossentropy', optimizer="adam",metrics=["accuracy"])

In [263]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 1.0000 - loss: 0.6671
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.6644
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.6616
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.6587
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.6557


**Interger Encode**

In [238]:
model=Sequential()
model.add(SimpleRNN(32,return_sequences=False, input_shape=(4,1)))
model.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [239]:
model.summary()

Model: "sequential_32"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_25 (SimpleRNN)       │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_27 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [240]:
model.compile(loss='binary_crossentropy', optimizer="adam",metrics=["accuracy"])

In [241]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.0000e+00 - loss: 0.8323
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.0000e+00 - loss: 0.7925
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.0000e+00 - loss: 0.7548
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7193
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6858


In [242]:
y_pred=model.predict(sequence)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step


In [243]:
y_pred

array([[0.57789546],
       [0.53264284]], dtype=float32)

In [244]:
len(X_train)

2